let carData = [
    {
        id: 0,
        carImg1: "./toyota_rv.JPG",
        carName: "Toyota RAV 4 (ID: 0)",
        manufacturingYear: 2021,
        seatingCapasity: "4",
        fuelType: "hybrid",
        milage: 6.1,
        transmission: "Automatic",
        price: 620,
    },
    {
        id: 1,
        carImg1: "./bmw_3_series.JPG",
        carName: "BMW 3 Series (ID: 1)",
        manufacturingYear: 2019,
        seatingCapasity: "4",
        fuelType: "Gasoline",
        milage: 8.2,
        transmission: "Automatic",
        price: 620,
    },
    {
        id: 2,
        carImg1: "./volks_wagen_t_cross.JPG",
        carName: "Volkswagen T-cross (ID: 2)",
        manufacturingYear: 2020,
        seatingCapasity: "4",
        fuelType: "hybrid",
        milage: 5.3,
        transmission: "Automatic",
        price: 620,
    },
    {
        id: 3,
        carImg1: "./cadilac_escalade.JPG",
        carName: "Cadillac Escalade (ID: 3)",
        manufacturingYear: 2020,
        seatingCapasity: "4",
        fuelType: "hybrid",
        milage: 7.7,
        transmission: "Automatic",
        price: 620,
    },
    {
        id: 4,
        carImg1: "./bmw_4_series_gti.JPG",
        carName: "BMW 4 Series GTI (ID: 4)",
        manufacturingYear: 2021,
        seatingCapasity: "4",
        fuelType: "hybrid",
        milage: 7.6,
        transmission: "Automatic",
        price: 620,
    },
    {
        id: 5,
        carImg1: "./bmw_4_saeries.JPG",
        carName: "BMW 4 Series (ID: 5)",
        manufacturingYear: 2019,
        seatingCapasity: "4",
        fuelType: "hybrid",
        milage: 7.2,
        transmission: "Automatic",
        price: 620,
    },
    {
        id: 6,
        carImg1: "./toyota_rv.JPG",
        carName: "Toyota RAV 4 (ID: 6)",
        manufacturingYear: 2021,
        seatingCapasity: "4",
        fuelType: "hybrid",
        milage: 6.1,
        transmission: "Automatic",
        price: 620,
    },
    {
        id: 7,
        carImg1: "./bmw_3_series.JPG",
        carName: "BMW 3 Series (ID: 7)",
        manufacturingYear: 2019,
        seatingCapasity: "4",
        fuelType: "Gasoline",
        milage: 8.2,
        transmission: "Automatic",
        price: 620,
    },
    {
        id: 8,
        carImg1: "./volks_wagen_t_cross.JPG",
        carName: "Volkswagen T-cross (ID: 8)",
        manufacturingYear: 2020,
        seatingCapasity: "4",
        fuelType: "hybrid",
        milage: 5.3,
        transmission: "Automatic",
        price: 620,
    },
    {
        id: 9,
        carImg1: "./cadilac_escalade.JPG",
        carName: "Cadillac Escalade (ID: 9)",
        manufacturingYear: 2020,
        seatingCapasity: "4",
        fuelType: "hybrid",
        milage: 7.7,
        transmission: "Automatic",
        price: 620,
    },
    {
        id: 10,
        carImg1: "./bmw_4_series_gti.JPG",
        carName: "BMW 4 Series GTI (ID: 10)",
        manufacturingYear: 2021,
        seatingCapasity: "4",
        fuelType: "hybrid",
        milage: 7.6,
        transmission: "Automatic",
        price: 620,
    },
    {
        id: 11,
        carImg1: "./bmw_4_saeries.JPG",
        carName: "BMW 4 Series (ID: 11)",
        manufacturingYear: 2019,
        seatingCapasity: "4",
        fuelType: "hybrid",
        milage: 7.2,
        transmission: "Automatic",
        price: 620,
    },
    {
        id: 12,
        carImg1: "./toyota_rv.JPG",
        carName: "Toyota RAV 4 (ID: 12)",
        manufacturingYear: 2021,
        seatingCapasity: "4",
        fuelType: "hybrid",
        milage: 6.1,
        transmission: "Automatic",
        price: 620,
    },
    {
        id: 13,
        carImg1: "./bmw_3_series.JPG",
        carName: "BMW 3 Series (ID: 13)",
        manufacturingYear: 2019,
        seatingCapasity: "4",
        fuelType: "Gasoline",
        milage: 8.2,
        transmission: "Automatic",
        price: 620,
    },
    {
        id: 14,
        carImg1: "./volks_wagen_t_cross.JPG",
        carName: "Volkswagen T-cross (ID: 14)",
        manufacturingYear: 2020,
        seatingCapasity: "4",
        fuelType: "hybrid",
        milage: 5.3,
        transmission: "Automatic",
        price: 620,
    },
    {
        id: 15,
        carImg1: "./cadilac_escalade.JPG",
        carName: "Cadillac Escalade (ID: 15)",
        manufacturingYear: 2020,
        seatingCapasity: "4",
        fuelType: "hybrid",
        milage: 7.7,
        transmission: "Automatic",
        price: 620,
    },
    {
        id: 16,
        carImg1: "./bmw_4_series_gti.JPG",
        carName: "BMW 4 Series GTI (ID: 16)",
        manufacturingYear: 2021,
        seatingCapasity: "4",
        fuelType: "hybrid",
        milage: 7.6,
        transmission: "Automatic",
        price: 620,
    },
    {
        id: 17,
        carImg1: "./bmw_4_saeries.JPG",
        carName: "BMW 4 Series (ID: 17)",
        manufacturingYear: 2019,
        seatingCapasity: "4",
        fuelType: "hybrid",
        milage: 7.2,
        transmission: "Automatic",
        price: 620,
    },
    {
        id: 18,
        carImg1: "./toyota_rv.JPG",
        carName: "Toyota RAV 4 (ID: 18)",
        manufacturingYear: 2021,
        seatingCapasity: "4",
        fuelType: "hybrid",
        milage: 6.1,
        transmission: "Automatic",
        price: 620,
    },
    {
        id: 19,
        carImg1: "./bmw_3_series.JPG",
        carName: "BMW 3 Series (ID: 19)",
        manufacturingYear: 2019,
        seatingCapasity: "4",
        fuelType: "Gasoline",
        milage: 8.2,
        transmission: "Automatic",
        price: 620,
    },
    {
        id: 20,
        carImg1: "./volks_wagen_t_cross.JPG",
        carName: "Volkswagen T-cross (ID: 20)",
        manufacturingYear: 2020,
        seatingCapasity: "4",
        fuelType: "hybrid",
        milage: 5.3,
        transmission: "Automatic",
        price: 620,
    },
    {
        id: 21,
        carImg1: "./cadilac_escalade.JPG",
        carName: "Cadillac Escalade (ID: 21)",
        manufacturingYear: 2020,
        seatingCapasity: "4",
        fuelType: "hybrid",
        milage: 7.7,
        transmission: "Automatic",
        price: 620,
    },
    {
        id: 22,
        carImg1: "./bmw_4_series_gti.JPG",
        carName: "BMW 4 Series GTI (ID: 22)",
        manufacturingYear: 2021,
        seatingCapasity: "4",
        fuelType: "hybrid",
        milage: 7.6,
        transmission: "Automatic",
        price: 620,
    },
    {
        id: 23,
        carImg1: "./bmw_4_saeries.JPG",
        carName: "BMW 4 Series (ID: 23)",
        manufacturingYear: 2019,
        seatingCapasity: "4",
        fuelType: "hybrid",
        milage: 7.2,
        transmission: "Automatic",
        price: 620,
    },
    {
        id: 24,
        carImg1: "./toyota_rv.JPG",
        carName: "Toyota RAV 4 (ID: 24)",
        manufacturingYear: 2021,
        seatingCapasity: "4",
        fuelType: "hybrid",
        milage: 6.1,
        transmission: "Automatic",
        price: 620,
    },
    {
        id: 25,
        carImg1: "./bmw_3_series.JPG",
        carName: "BMW 3 Series (ID: 25)",
        manufacturingYear: 2019,
        seatingCapasity: "4",
        fuelType: "Gasoline",
        milage: 8.2,
        transmission: "Automatic",
        price: 620,
    },
    {
        id: 26,
        carImg1: "./volks_wagen_t_cross.JPG",
        carName: "Volkswagen T-cross (ID: 26)",
        manufacturingYear: 2020,
        seatingCapasity: "4",
        fuelType: "hybrid",
        milage: 5.3,
        transmission: "Automatic",
        price: 620,
    },
    {
        id: 27,
        carImg1: "./cadilac_escalade.JPG",
        carName: "Cadillac Escalade (ID: 27)",
        manufacturingYear: 2020,
        seatingCapasity: "4",
        fuelType: "hybrid",
        milage: 7.7,
        transmission: "Automatic",
        price: 620,
    },
    {
        id: 28,
        carImg1: "./bmw_4_series_gti.JPG",
        carName: "BMW 4 Series GTI (ID: 28)",
        manufacturingYear: 2021,
        seatingCapasity: "4",
        fuelType: "hybrid",
        milage: 7.6,
        transmission: "Automatic",
        price: 620,
    },
    {
        id: 29,
        carImg1: "./bmw_4_saeries.JPG",
        carName: "BMW 4 Series (ID: 29)",
        manufacturingYear: 2019,
        seatingCapasity: "4",
        fuelType: "hybrid",
        milage: 7.2,
        transmission: "Automatic",
        price: 620,
    },
    {
        id: 30,
        carImg1: "./toyota_rv.JPG",
        carName: "Toyota RAV 4 (ID: 30)",
        manufacturingYear: 2021,
        seatingCapasity: "4",
        fuelType: "hybrid",
        milage: 6.1,
        transmission: "Automatic",
        price: 620,
    },
    {
        id: 31,
        carImg1: "./bmw_3_series.JPG",
        carName: "BMW 3 Series (ID: 31)",
        manufacturingYear: 2019,
        seatingCapasity: "4",
        fuelType: "Gasoline",
        milage: 8.2,
        transmission: "Automatic",
        price: 620,
    },
    {
        id: 32,
        carImg1: "./volks_wagen_t_cross.JPG",
        carName: "Volkswagen T-cross (ID: 32)",
        manufacturingYear: 2020,
        seatingCapasity: "4",
        fuelType: "hybrid",
        milage: 5.3,
        transmission: "Automatic",
        price: 620,
    },
    {
        id: 33,
        carImg1: "./cadilac_escalade.JPG",
        carName: "Cadillac Escalade (ID: 33)",
        manufacturingYear: 2020,
        seatingCapasity: "4",
        fuelType: "hybrid",
        milage: 7.7,
        transmission: "Automatic",
        price: 620,
    },
    {
        id: 34,
        carImg1: "./bmw_4_series_gti.JPG",
        carName: "BMW 4 Series GTI (ID: 34)",
        manufacturingYear: 2021,
        seatingCapasity: "4",
        fuelType: "hybrid",
        milage: 7.6,
        transmission: "Automatic",
        price: 620,
    },
    {
        id: 35,
        carImg1: "./bmw_4_saeries.JPG",
        carName: "BMW 4 Series (ID: 35)",
        manufacturingYear: 2019,
        seatingCapasity: "4",
        fuelType: "hybrid",
        milage: 7.2,
        transmission: "Automatic",
        price: 620,
    },
    {
        id: 36,
        carImg1: "./toyota_rv.JPG",
        carName: "Toyota RAV 4 (ID: 36)",
        manufacturingYear: 2021,
        seatingCapasity: "4",
        fuelType: "hybrid",
        milage: 6.1,
        transmission: "Automatic",
        price: 620,
    },
    {
        id: 37,
        carImg1: "./bmw_3_series.JPG",
        carName: "BMW 3 Series (ID: 37)",
        manufacturingYear: 2019,
        seatingCapasity: "4",
        fuelType: "Gasoline",
        milage: 8.2,
        transmission: "Automatic",
        price: 620,
    },
    {
        id: 38,
        carImg1: "./volks_wagen_t_cross.JPG",
        carName: "Volkswagen T-cross (ID: 38)",
        manufacturingYear: 2020,
        seatingCapasity: "4",
        fuelType: "hybrid",
        milage: 5.3,
        transmission: "Automatic",
        price: 620,
    },
    {
        id: 39,
        carImg1: "./cadilac_escalade.JPG",
        carName: "Cadillac Escalade (ID: 39)",
        manufacturingYear: 2020,
        seatingCapasity: "4",
        fuelType: "hybrid",
        milage: 7.7,
        transmission: "Automatic",
        price: 620,
    },
    {
        id: 40,
        carImg1: "./bmw_4_series_gti.JPG",
        carName: "BMW 4 Series GTI (ID: 40)",
        manufacturingYear: 2021,
        seatingCapasity: "4",
        fuelType: "hybrid",
        milage: 7.6,
        transmission: "Automatic",
        price: 620,
    },
    {
        id: 41,
        carImg1: "./bmw_4_saeries.JPG",
        carName: "BMW 4 Series (ID: 41)",
        manufacturingYear: 2019,
        seatingCapasity: "4",
        fuelType: "hybrid",
        milage: 7.2,
        transmission: "Automatic",
        price: 620,
    },
    {
        id: 42,
        carImg1: "./toyota_rv.JPG",
        carName: "Toyota RAV 4 (ID: 42)",
        manufacturingYear: 2021,
        seatingCapasity: "4",
        fuelType: "hybrid",
        milage: 6.1,
        transmission: "Automatic",
        price: 620,
    },
    {
        id: 43,
        carImg1: "./bmw_3_series.JPG",
        carName: "BMW 3 Series (ID: 43)",
        manufacturingYear: 2019,
        seatingCapasity: "4",
        fuelType: "Gasoline",
        milage: 8.2,
        transmission: "Automatic",
        price: 620,
    },
    {
        id: 44,
        carImg1: "./volks_wagen_t_cross.JPG",
        carName: "Volkswagen T-cross (ID: 44)",
        manufacturingYear: 2020,
        seatingCapasity: "4",
        fuelType: "hybrid",
        milage: 5.3,
        transmission: "Automatic",
        price: 620,
    },
    {
        id: 45,
        carImg1: "./cadilac_escalade.JPG",
        carName: "Cadillac Escalade (ID: 45)",
        manufacturingYear: 2020,
        seatingCapasity: "4",
        fuelType: "hybrid",
        milage: 7.7,
        transmission: "Automatic",
        price: 620,
    },
    {
        id: 46,
        carImg1: "./bmw_4_series_gti.JPG",
        carName: "BMW 4 Series GTI (ID: 46)",
        manufacturingYear: 2021,
        seatingCapasity: "4",
        fuelType: "hybrid",
        milage: 7.6,
        transmission: "Automatic",
        price: 620,
    },
    {
        id: 47,
        carImg1: "./bmw_4_saeries.JPG",
        carName: "BMW 4 Series (ID: 47)",
        manufacturingYear: 2019,
        seatingCapasity: "4",
        fuelType: "hybrid",
        milage: 7.2,
        transmission: "Automatic",
        price: 620,
    },
    {
        id: 48,
        carImg1: "./toyota_rv.JPG",
        carName: "Toyota RAV 4 (ID: 48)",
        manufacturingYear: 2021,
        seatingCapasity: "4",
        fuelType: "hybrid",
        milage: 6.1,
        transmission: "Automatic",
        price: 620,
    },
    {
        id: 49,
        carImg1: "./bmw_3_series.JPG",
        carName: "BMW 3 Series (ID: 49)",
        manufacturingYear: 2019,
        seatingCapasity: "4",
        fuelType: "Gasoline",
        milage: 8.2,
        transmission: "Automatic",
        price: 620,
    },
    
];

module.exports = carData;
